"""empty message

Revision ID: 04745a812c60
Revises: db86ee18dee7
Create Date: 2020-04-05 01:32:35.989434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04745a812c60'
down_revision = 'db86ee18dee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
